### ISSUE TITLE
Login exception - remote name

### ISSUE THREAD

**Issue by Woren** [doodz/Youtrack-for-visual-studio#1]
I'm getting exception during login:
"the remote name could not be resolved: rest"
(same exception as for non existing url)

My server url is like https://youtrack.xyz.cz:8082 (port included)

This url is working with Android Studio / IntelliJ IDE Youtrack plugin with no problems.

Visual Studio Professional 2017 - 15.4.4, Windows 10

**Comment by doodz** [comment]
bug fixed on 0.0.3
