### ISSUE TITLE
click issue id gives `url//issueid`

### ISSUE THREAD

**Issue by YoungjaeKim** [doodz/Youtrack-for-visual-studio#2]
In issue detail view, clicking `#ID-222` gives `{url}//{issueid}` so to make NotFound error in web browser.
It would be great to replace `//` to `/` before calling web browser.

**Comment by doodz** [comment]
https://github.com/doodz/Youtrack-for-visual-studio/commit/eed2e6b4e34febbafee8e0ab50f9bf78ac81645e
